name: 3IXBuilding
version: '${version}'
main: dev.thebjoredcraft.building.Building3IX
api-version: '1.20'
author: TheBjoRedCraft
commands:
  speed:
    permission: building.speed.command
  logger:
    permission: building.logger.command
  bworld:
    permission: building.world.command
